@jwt=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4OTIyMjZ9.TUmvfWWhjt98lay5b_4HacPxQMKvqrI9_w1lHoX88E8




### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "email": "test4@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "password"
}



### RECIPIES INDEX
GET http://localhost:3000/recipes.json
Authorization: Bearer {{jwt}}

### RECIPES SHOW
GET http://localhost:3000/recipes/3.json
Authorization: Bearer {{jwt}}


### INGREDIENTS INDEX
GET http://localhost:3000/ingredients.json
Authorization: Bearer {{jwt}}

### FAVORITES CREATE
POST http://localhost:3000/favorites.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "recipe_id": 3
 
}

### FAVORITES INDEX
GET http://localhost:3000/favorites.json
Authorization: Bearer {{jwt}}
