@jwt=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTE5NTUwMjl9.gLggZ4llUnFAuKNTZg5a_Ix8Aa5C4ySdCPoJniPTCb4




### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "password"
}

# ### Photos create
# POST http://localhost:3000/photos.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
# Content-Type: application/json

# {
#   "name": "Test name",
#   "width": 640,
#   "height": 480
# }

### RECIPIES INDEX
GET http://localhost:3000/recipes.json
Authorization: Bearer {{jwt}}

### RECIPES SHOW
GET http://localhost:3000/recipes/1.json
Authorization: Bearer {{jwt}}


### INGREDIENTS INDEX
GET http://localhost:3000/ingredients.json
Authorization: Bearer {{jwt}}

### FAVORITES CREATE
POST http://localhost:3000/favorites.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "recipe_id": 1
 }